import java.util.ArrayList;
import java.util.List;

/**
 * ASTNode represents a node in the Abstract Syntax Tree
 * generated by the parser from tokenized input.
 */
public class ASTNode {
    private String nodeType;
    private String value;
    private List<ASTNode> children;
    private int depth;

    /**
     * Constructor for ASTNode
     * @param nodeType The type of AST node (STATEMENT, EXPRESSION, ASSIGNMENT, etc.)
     * @param value The value or content of the node
     * @param depth The depth in the tree
     */
    public ASTNode(String nodeType, String value, int depth) {
        this.nodeType = nodeType;
        this.value = value;
        this.depth = depth;
        this.children = new ArrayList<>();
    }

    // Getters and setters
    public String getNodeType() {
        return nodeType;
    }

    public String getValue() {
        return value;
    }

    public int getDepth() {
        return depth;
    }

    public List<ASTNode> getChildren() {
        return children;
    }

    public void addChild(ASTNode child) {
        children.add(child);
    }

    /**
     * Pretty print the AST
     * @return String representation of the tree
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        appendTree(sb, 0);
        return sb.toString();
    }

    private void appendTree(StringBuilder sb, int indent) {
        sb.append(" ".repeat(indent * 2))
          .append(nodeType)
          .append(": ")
          .append(value)
          .append("\n");
        for (ASTNode child : children) {
            child.appendTree(sb, indent + 1);
        }
    }
}
